# Multispecies GLV: assembly and invasibility {#multi}

We have seen in the previous lecture that a large ecological community will almost invariably be unstable, possibly leading to extinctions. It is therefore natural to ask what happens when either a feasible equilibrium does not exist, or it is unstable. In particular, we want to know how many species can persist.

## Assembly

We call assembly the process by which a community is constituted by adding species sequentially. Imagine starting with a bare environment, and introduce the first species. If the species can grow in the new environment, it will establish, and if not, it will go extinct. Mathematically, we assume that new species are introduced at very low abundance, so that they do not experience self-limitation due to crowding, and that invasion are spaced in time so that the dynamics can play out before the next invasion. For example, consider

$$
\dfrac{1}{x_i(t)}\dfrac{dx_i(t)}{dt} = r_i + \sum_j A_{ij} x_j(t)
$$
If the species is grown by itself, and we discard the quadratic effect, we have that initially:

$$
\dfrac{1}{x_i(t)}\dfrac{dx_i(t)}{dt} \approx r_i
$$

That is, the species will establish if it has a positive growth rate in the environment. Suppose that this is the case: the species 1 will then grow to its equilibrium abundance $x_i^\star$. Now add a second species. Its initial per-capita growth rate is going to be:

$$
\dfrac{1}{x_j(t)}\dfrac{dx_j(t)}{dt} = r_j + \sum_k A_{jj} x_k(t) \approx r_j + A_{ji}x_i^\star
$$

The species $j$ can therefore growth when rare if $r_j + A_{ji}x_i^\star > 0$, i.e., $r_j > -A_{ji}x_i^\star$. If the species $j$ can grow when rare, it could a) grow initially, but then go extinct; b) displace species $i$, sending it to extinction; c) coexist with species $i$. 
## Number of coexisting species: a random zoo

We can generalize the notions above to multiple species, by making a strong assumption on the matrix $A$. If the matrix $A$ is diagonally stable, we have seen before that all trajectories started at a positive point will converge to a unique equilibrium $x^\star$. At equilibrium, some of the species will have positive abundance, while other abundance zero. 

```{r, randomzoo}
library(tidyverse)
# code to solve for the equilibrium without integration
source("https://raw.githubusercontent.com/StefanoAllesina/randomzoo/master/R/lemke-howson.R")

# draw a random symmetric matrix, and make it stable
# (and therefore diagonally stable)
# with off-diagonals with mean zero
build_random_symmetric_stable_matrix <- function(n){
  A <- matrix(0, n, n)
  A[upper.tri(A)] <- rnorm(n * (n - 1) / 2)
  # make symmetric
  A <- A + t(A)
  # now find the largest eigenvalue
  l1A <- max(eigen(A, only.values = TRUE, symmetric = TRUE)$values)
  # set the diagonal to make it stable
  diag(A) <- -1.01 * l1A
  return(A)
}
```

